[project]
name = "spar-causal-probes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "ipykernel>=7.2.0",
    "torch>=2.10.0",
    "transformers>=5.2.0",
]
